image: kindest/node:v1.32.1@sha256:6afef2b7f69d627ea7bf27ee6696b6868d18e03bf98167c420df486da4662db6

gardener:
  apiserverRelay:
    deployed: false
  controlPlane:
    deployed: true
    kindIsGardenCluster: true
    customEtcdStatefulSet: true
  nginxIngress:
    deployed: true
  seed:
    deployed: true
    istio:
      listenAddresses:
      - 172.18.255.1
  repositoryRoot: "."
  garden:
    deployed: false

backupBucket:
  deployed: true

registry:
  deployed: true

networking:
  ipFamily: ipv4
  podSubnet: 10.1.0.0/16
  serviceSubnet: 10.2.0.0/16

#workers:
#- zone: "1"
#- zone: "2"
